# Site settings
title: Max Blog
header-img: img/home-bg.png
email: meingorn@gmail.com
copyright_name: meingorn
description: > # this means to ignore newlines until "baseurl:"
  Maximum Blogage
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  meingorn
learn_profile: meingorn
email_username: meingorn@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
